# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs: 
  aws-eks: circleci/aws-eks@2.1.0
  kubernetes: circleci/kubernetes@1.0


commands:
  # TODO: adapt to project
  destroy-eks-cluster-stack:
    description: Destroy EKS Cluster Stack.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack \
            --stack-name eksctl-ML-APP-CLUSTER-cluster
jobs:
  build_app:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            echo "Virtual Environment created, now installing requirments..."
            make install
            # Install hadolint
            echo "Requirements installed, now installing hadolint..."
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
          - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  # ToDo
  # OPTIONAL
  # create unit test of app 
  # run app locally and send dummy request to API
  # use unit test to verify expected result
  # test_app:

  # ToDo
  # store in AWS image repository -> AWS ECR
  build_container:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            docker build --tag=ml-app-local .
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install --upgrade awscli
            echo 'aws cli version:'
            aws --version   
      - run:
          name: authenticate and upload docker image to AWS ECR
          command: |
            # to local docker image to central path
            docker image tag ml-app-local:latest $DOCKERPATH
            # Retrieve an authentication token and authenticate your Docker client to your registry.
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
            # Push Docker image to AWS ECR repository
            docker push $DOCKERPATH

  # ToDo
  # optional element -> e.g. security scanning of Docker container
  # scan_container:  


# ToDo
  # create AWS Kubernetes Cluster -> AWS EKS
  # include circleci id in stack names
  create_eks_cluster:  
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # install tar utility
            yum install -y tar gzip
      - aws-eks/setup:
          version: 0.80.0
      - kubernetes/install
      - run:
          name: check installs
          command: |
            eksctl version
            kubectl config view
      - run:
          name: created managed Kubernetes cluster via AWS Fargate
          command: |
            # create managed cluster on AWS Fargate
            eksctl create cluster \
            --name ${EKS_CLUSTER_NAME} \
            --region ${AWS_REGION} \
            --zones ${AWS_REGION}a,${AWS_REGION}b \
            --fargate
            # View Kubernetes resources
            kubectl get nodes -o wide
            # View the workloads running on the cluster
            kubectl get pods --all-namespaces -o wide
            # create Fargate profile ml-app -> see https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html
            eksctl create fargateprofile \
            --cluster ${EKS_CLUSTER_NAME} \
            --name fargate_profile_ml-app \
            --namespace ml-app \
            --region ${AWS_REGION}
            # verify that profile was created
            aws eks list-fargate-profiles \
            --cluster-name ${EKS_CLUSTER_NAME} \
            --region ${AWS_REGION}
      - destroy-eks-cluster-stack

  # ToDo
  setup_eks_loadbalancer: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # install tar utility
            yum install -y tar gzip
            # install openssl
            yum install -y openssl
      - aws-eks/setup:
          version: 0.80.0
      - kubernetes/install
      - run:
          name: install helm
          command: |
            curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
            helm version --short
            helm repo add stable https://charts.helm.sh/stable
            # helm completion bash >> ~/.bash_completion
            # . /etc/profile.d/bash_completion.sh
            # . ~/.bash_completion
            # source <(helm completion bash)
      - run:
          name: check installs
          command: |
            helm version
            eksctl version
            kubectl config view
      - run:
          name: create IAM OIDC provider
          command: |
            eksctl utils associate-iam-oidc-provider \
            --region ${AWS_REGION} \
            --cluster ${EKS_CLUSTER_NAME} \
            --approve
      - run:
          name: create IAM policy
          command: |
            curl -o iam_policy.json https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.2.0/docs/install/iam_policy.json
            aws iam create-policy \
                --policy-name AWSLoadBalancerControllerIAMPolicy \
                --policy-document file://iam_policy.json
            rm iam_policy.json
      - run:
          name: Create a IAM role and ServiceAccount for the Load Balancer controller
          command: |
            eksctl create iamserviceaccount \
            --cluster ${EKS_CLUSTER_NAME} \
            --namespace kube-system \
            --name aws-load-balancer-controller \
            --attach-policy-arn arn:aws:iam::${AWS_ACCOUNT_ID}:policy/AWSLoadBalancerControllerIAMPolicy \
            --override-existing-serviceaccounts \
            --region ${AWS_REGION} \
            --approve
      - run:
          name: Install the TargetGroupBinding CRDs
          command: |
            kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller/crds?ref=master"
      - run:
          name: Deploy the Helm chart from the Amazon EKS charts repo
          command: |
            # verify if AWS Load Balancer version has been set -> https://www.eksworkshop.com/020_prerequisites/k8stools/#set-the-aws-load-balancer-controller-version
            if [ ! -x ${LBC_VERSION} ]
              then
                tput setaf 2; echo '${LBC_VERSION} has been set.'
              else
                tput setaf 1;echo '${LBC_VERSION} has NOT been set.'
            fi
            # deploy Helm chart
            helm repo add eks https://aws.github.io/eks-charts
            export VPC_ID=$(aws eks describe-cluster \
                            --name ${EKS_CLUSTER_NAME} \
                            --query "cluster.resourcesVpcConfig.vpcId" \
                            --region ${AWS_REGION} \
                            --output text)
            helm upgrade -i aws-load-balancer-controller \
                eks/aws-load-balancer-controller \
                -n kube-system \
                --set clusterName=${EKS_CLUSTER_NAME} \
                --set serviceAccount.create=false \
                --set serviceAccount.name=aws-load-balancer-controller \
                --set image.tag="${LBC_VERSION}" \
                --set region=${AWS_REGION} \
                --set vpcId=${VPC_ID}
      - run:
          name: Check if deployment has completed
          command: |
            kubectl -n kube-system rollout status deployment aws-load-balancer-controller

      # - run:
      #     name: install prerequisites
      #     command: |
      #       # install HELM -> https://www.eksworkshop.com/beginner/060_helm/helm_intro/install/index.html
      #       # done via orb
      # - run:
      #     name: install prerequisites
      #     command: |
      #       # TODO -> https://www.eksworkshop.com/beginner/180_fargate/prerequisites-for-alb/

  # ToDo
  deploy_container: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: create namespace
          command: |
            kubectl create namespace ml-app
      - run:
          name: deploy container to Fargate cluster
          command: |
            kubectl apply -f fargate_deployment.yaml
            # list all resources in namespace
            kubectl get all -n ml-app
      # - run:
      #     name: create service
      #     command: |
      #       kubectl apply -f fargate_service.yaml
      #       # describe details of service
      #       kubectl -n ml-app describe service ml-app-service
      #       # view details of pod ml-app-deployment-6c76c467-c5pbd
      #       kubectl -n ml-app describe pod ml-app-deployment-6c76c467-c5pbd
      # - run:
      #     name: expose deployment of type LoadBalancer
      #     command: |
      #       # kubectl expose deployment ml-app-deployment \
      #       # --type=LoadBalancer \
      #       # --name=ml-app-loadbalancer \
      #       # -n ml-app
      #       kubectl expose deployment ml-app-deployment \
      #       --type=NodePort  \
      #       --name=ml-app-service-exposed\
      #       -n ml-app
      #       # get information about service
      #       kubectl get service/ml-app-loadbalancer \
      #       -n ml-app \
      #       |  awk {'print $1" " $2 " " $4 " " $5'} | column -t
      #       # list services
      #       kubectl get svc -n ml-app


  # ToDo
  # create AWS Kubernetes Cluster -> AWS EKS
  # include circleci id in stack names
  # create_network_infrastructure:  
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: create VPCs, IAM role and EKS Cluster
  #         command: |
  #           ID=${CIRCLE_WORKFLOW_ID:0:7}
  #           aws cloudformation deploy \
  #             --template-file infrastructure/eks-vpc-role-cluster.yaml \
  #             --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"\
  #             --tags project=ml-app \
  #             --stack-name "ml-app-eks-cluster-${ID}" \
  #             --parameter-overrides \
  #             ID="${ID}" \
  #             EKSClusterName="${ID}-ML-APP-CLUSTER" 

  # create_eks_cluster:  
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: create worker node group for EKS Cluster
  #         command: |
  #           ID=${CIRCLE_WORKFLOW_ID:0:7}
  #           aws cloudformation deploy \
  #             --template-file infrastructure/eks-nodegroup.yaml \
  #             --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"\
  #             --tags project=ml-app \
  #             --stack-name "ml-app-eks-worker-${ID}" \
  #             --parameter-overrides \
  #             ID="${ID}" \
  #             KeyName="EKSworkerKeyPair" \
  #             ClusterName="${ID}-ML-APP-CLUSTER" \
  #             NodeGroupName="${ID}-ML-APP-NODEGROUP"

  # ToDo
  # deploy_container: 
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install dependencies
  #         command: |
  #           # TODO install and start docker
  #           yum update -y
  #           yum install docker -y
  #           service docker start
  #     - run: 
  #         name: create kubeconfig for EKS
  #         command: |
  #           ID=${CIRCLE_WORKFLOW_ID:0:7}
  #           aws eks list-clusters
  #           aws eks update-kubeconfig --region us-east-1 --name "${ID}-ML-APP-CLUSTER"
  #           aws get svc
  #     - run: 
  #         name: deploy container to EKS Cluster
  #         command: |
  #           kubectl apply -f eks_deployment.yaml
  #           kubectl get deployments

  # ToDo
  # smoketest_app:  

  # ToDo
  # use cloudfront for production container
  # prod_promotion:  

  # ToDo
  # delete no longer required resources
  # cleanup:  

workflows:
  default:
    jobs:
      - setup_eks_loadbalancer
      # - build_app
      # # - test_app # optional
      # - build_container:
      #     requires: [build_app]
      # - scan_container # optional

      # TODO: complete steps
      # - create_eks_cluster:
      #     requires: [build_app]
      #     filters:
      #       branches:
      #         only: [master]
      # - setup_eks_loadbalancer:
      #     requires: [create_eks_cluster]
      # - deploy_container:
      #     requires: [setup_eks_loadbalancer]
      # - smoketest_app:
      #     requires: [deploy_container]
      # - prod_promotion:
      #     requires: [smoketest_app]
      # - cleanup:
      #     requires: [prod_promotion]
