# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

commands:
  # TODO: adapt to project
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string  
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws s3 rb --force s3://udapeople-<< parameters.workflow_id >>
            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>  


jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            echo "Virtual Environment created, now installing requirments..."
            make install
            # Install hadolint
            echo "Requirements installed, now installing hadolint..."
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
          - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  # ToDo
  # OPTIONAL
  # create unit test of app 
  # run app locally and send dummy request to API
  # use unit test to verify expected result
  # test_app:

  # ToDo
  # store in AWS image repository -> AWS ECR
  build_container:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # TODO install docker
      - run:
          name: build docker image
          command: |
            docker build --tag=ml-app-local .
      - run:
          name: authenticate and upload docker image to AWS ECR
          command: |
            # Create dockerpath
            # TODO: handover dockerpath variable instead of hardcording
            DOCKERPATH=017792502591.dkr.ecr.us-east-1.amazonaws.com/ml_app:latest
            # to local docker image to central path
            docker image tag ml-app-local:latest $DOCKERPATH
            # Retrieve an authentication token and authenticate your Docker client to your registry.
            aws ecr get-login-password --region region | docker login --username AWS --password-stdin aws_account_id.dkr.ecr.region.amazonaws.com
            # Push Docker image to AWS ECR repository
            docker push $DOCKERPATH

  # ToDo
  # optional element -> e.g. security scanning of Docker container
  # scan_container:  

  # ToDo
  # create AWS Kubernetes Cluster -> AWS EKS
  # include circleci id in stack names
  # create_infrastructure:  

  # ToDo
  # smoketest_app:  

  # ToDo
  # use cloudfront for production container
  # prod_promotion:  

  # ToDo
  # delete no longer required resources
  # cleanup:  

workflows:
  default:
    jobs:
      - build
      # - test_app # optional
      - build_container
      # - scan_container # optional
      - create_infrastructure
      - deploy_containter
      - smoketest_app
      - prod_promotion
      - cleanup
