Description: >
  Cloudfront distribution for ML App.

Parameters:
  PublicIP:
    Description: Unique identifier.
    Type: String


Resources:
  
  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${PublicIP}"
            Id: ml-app-api
            CustomOriginConfig:
              HTTPPort: 80
              HTTPPort: 80
              OriginProtocolPolicy: match-viewer
        Enabled: True
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: ml-app-api
          ViewerProtocolPolicy: allow-all

Outputs:
  PublicIP:
    Value: !Sub ${PublicIP}
    Description: URL for ML app API
    Export:
      Name: PublicIP
